#!/bin/bash
#----------------------------------------------------
# Sample Slurm job script
#   for TACC Stampede2 SKX nodes
#
#   *** MPI Job on SKX Normal Queue ***
# 
# Last revised: 20 Oct 2017
#
# Notes:
#
#   -- Launch this script by executing
#      "sbatch skx.mpi.slurm" on Stampede2 login node.
#
#   -- Use ibrun to launch MPI codes on TACC systems.
#      Do not use mpirun or mpiexec.
#
#   -- Max recommended MPI ranks per SKX node: 48
#      (start small, increase gradually).
#
#   -- If you're running out of memory, try running
#      fewer tasks per node to give each task more memory.
#
#----------------------------------------------------

#SBATCH -J test            # Job name
#SBATCH -o test.o          # Name of stdout output file
#SBATCH -e test.e          # Name of stderr error file
#SBATCH -p skx-normal      # Queue (partition) name
#SBATCH -N 1               # Total # of nodes 
#SBATCH -n 1               # Total # of mpi tasks
#SBATCH -t 00:30:00        # Run time (hh:mm:ss)
#SBATCH --mail-user=everett.165@osu.edu
#SBATCH --mail-type=all    # Send email at begin and end of job
#SBATCH -A TG-PHY180024    # Allocation name (STARTUP ALLOC)

# Other commands must follow all #SBATCH directives...

#cd to work drive
cd $WORK

#cd to JETSCAPE working directory 
cd JETSCAPE-COMP
cd test

#prepare some environment variables and load necessary modules
module load intel/18.0.2 cmake/3.7.1 gsl boost hdf5 eigen impi 
source ../sims_scripts/prepare_compilation_stampede2_2.sh
module list

pwd

date


# first arg is minimum total number of hadrons after oversampling
# second arg is number of cpu cores assigned to this event 
python Run_Event.py 1000 1          # Use ibrun instead of mpirun or mpiexec

# ---------------------------------------------------
