Logging:
    default: INFO

General:
    Modus:         Box
    Time_Step_Mode: Fixed
    Delta_Time:    0.1
    End_Time:      200.0
    Randomseed:    -1
    Nevents:       1

Output:
    Output_Interval: 5.0
    Particles:
        Format:          ["Oscar2013"]
        Only_Final: False

Modi:
    Box:
        Length: 10.0
        Temperature: 0.15
        Initial_Condition: "thermal momenta"
        Start_Time: 0.0
        # The box is initialized with the particles listed in particles.txt
        # according to their expected thermal multiplicities at the termperature
        # specified above.
        Use_Thermal_Multiplicities: True

Collision_Term:
    Force_Decays_At_End: False
    Strings: False
    NNbar_Treatment: "resonances"
    Elastic_NN_Cutoff_Sqrts: 1.8
