Logging:
    default: INFO

General:
    Modus:  Afterburner   # Dummy, but some value has to be present
    Time_Step_Mode: Fixed
    Delta_Time:    0.5
    End_Time:      100.0  # Reset from the JetScape xml config
    Randomseed:    -1     # Reset from the JetScape xml config
    Nevents:       1      # Dummy

Output:
    Output_Interval:  5.0

# This section is dummy
Modi:
    List:
        File_Directory: .
        File_Prefix: "dummy"
        Shift_Id: 0
        Start_Time: 0.0
